### ISSUE TITLE
[Problem] Icon missing on ubuntu deb install

### ISSUE THREAD

**Issue by torgeros** [jonasmusall/texpaste#17]
### Version

1.2.0

### Operating System

Ubuntu 22.04 LTS

### Problem Description

The gnome shell displays the (system default) gear icon instead of texpaste's own logo as it's app icon.

![icon in gnome app launcher](https://user-images.githubusercontent.com/67151313/195901864-de8c1401-fb48-4cdf-9f3e-27b14e6d42a0.png)

The created desktop file looks like the following, I guess the icon either can not be or is not correctly retrieved from the executable. The `Icon=...` usually contains the path to an image file.

```plain
[Desktop Entry]
Name=texpaste
Exec=/opt/texpaste/texpaste %U
Terminal=false
Type=Application
Icon=texpaste
StartupWMClass=texpaste
Comment=Live TeX rendering.
Categories=Utility;
```

**Comment by jonasmusall** [comment]
According to the [electron-builder docs](https://www.electron.build/configuration/linux) the `icon` key should take care of this. However it is also possible to supply custom desktop file entries, which might be a way to fix this issue. How these entries should be entered is not clear to me ("name to value" = ?).

**Comment by jonasmusall** [comment]
https://specifications.freedesktop.org/icon-theme-spec/icon-theme-spec-latest.html

**Comment by jonasmusall** [comment]
This is a bug in electron-builder: electron-userland/electron-builder#5294. A workaround seems to be to place icon files named after their size in a subdirectory in `build` and use that as a value for the icon key, e.g.

```jsonc
{
  // ...
  "build": {
    // ...
    "linux": {
      // ...
      "icon": "build/icons"
    }
  }
}
```

**Comment by jonasmusall** [comment]
Additionally it would be nice to have an SVG icon which should be packed as `usr/share/icons/hicolor/scalable/apps/texpaste.svg`. Not sure if electron-builder supports this, but if it doesn't it should be possible to manually add it to the DEB using `dpkg-deb`.
